Cc 21 display menu options
AshokkSS/Crypto-CLI-Tool pull request #6
Opened 2022-09-27 15:41 UTC by AshokkSS

Completed ticket as described.
Menu options are clearly displayed.

2022-09-27 15:59 UTC, Dark-Raine requested changes

2022-09-27 15:59 UTC, Dark-Raine commented on .results.json
> +{"version":"3.11.0","messages":["\nAn error occurred while loading ./spec/run_spec.rb.\n\u001b[31mFailure/Error: \u001b[0m\u001b[1;32m$result\u001b[0m = \u001b[1;34;4mPROMPT\u001b[0m.select(\u001b[31
Do we need to store this file in git?

2022-09-27 15:59 UTC, Dark-Raine commented on lib/run.rb
> +PING_URL = "https://api.coingecko.com/api/v3/ping"
Could this live in it's own class where it's domain is just to do with connecting with the poke api?

2022-09-27 15:59 UTC, Dark-Raine commented on lib/run.rb
> +OPTIONS =  %w(Price_Check Compare_Cryptos My_Portfolio Close)
Could these options not be bart of the main menu class?

2022-09-27 15:59 UTC, Dark-Raine commented on lib/run.rb
> +    end
This could be apart of the poke api class mentioned above

2022-09-27 15:59 UTC, Dark-Raine commented on lib/run.rb
> +    end
Same thing for these

2022-09-27 15:59 UTC, Dark-Raine commented on lib/run.rb
> +#   end
delete commented code

2022-09-27 15:59 UTC, Dark-Raine commented on lib/run.rb
> +
remove whitespace from files

2022-09-27 15:59 UTC, Dark-Raine commented on spec/run_spec.rb
> +# end
delete commented out code

2022-09-27 16:01 UTC, Dark-Raine commented
Another thing to add, you haven't commited your gemfile and gemfile.lock. These are important in ensuring you always use the correct versions of the gems in your application

2022-09-27 16:25 UTC, AshokkSS commented
Have made those changes now, just a few things.
I have added *.json to the gitignore but can still see it in my repo.
I can see the gem file is in the git?

2022-09-29 12:58 UTC, Dark-Raine approved these changes

2022-09-29 12:59 UTC, merged